- name: Clean artifact path
  file:
    state: absent
    path: /var/www/html/laravel

- git:
    repo: https://github.com/laravel/laravel.git
    dest: /var/www/html/laravel
    version: v5.7.19

- composer:
    command: install
    working_dir: /var/www/html/laravel
  tags: composer
  environment:
    HOME: /home/ubuntu/
  sudo: yes
  sudo_user: ubuntu

- name: create .env file
  tags: env
  shell: cd /var/www/html/laravel; mv .env.example .env

- name: create application key
  tags: key
  shell: cd /var/www/html/laravel; php artisan key:generate